decoderslash_erp/Controllers/EmployeeDashBoardController.cs
using decoderslash_erp.Data;
using decoderslash_erp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using Microsoft.EntityFrameworkCore;
using System.Text;
using System.Text.Json;

namespace decoderslash_erp.Controllers
{
    public class EmployeeDashBoardController : Controller
    {
        private readonly decoderslash_erpContext _context;

        public EmployeeDashBoardController(decoderslash_erpContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Cred") == null)
                return RedirectToAction("Index", "Login");
            String? cake = HttpContext.Session.GetString("Data");
            Employee emp = JsonSerializer.Deserialize<Employee>(cake!)!;

            DashBoard dashBoard = new DashBoard();
            dashBoard.employee = emp;

            List<CardSectionModel> AllSections = new List<CardSectionModel>();

            if (emp.Designation == "Admin")
            {
                AllSections = DashBoardRepository.MakeAdminSectionsList();
            }
            else if (emp.Designation == "Employee")
            {
                AllSections = DashBoardRepository.MakeEmployeeSectionsList();
            }
            else if (emp.Designation == "Project_Manager")
            {
                AllSections = DashBoardRepository.MakeProjectManagerSectionsList();
            }
            dashBoard.controls = AllSections;

            return View(dashBoard!);
        }
    }
}

decoderslash_erp/Views/EmployeeDashBoard/ShowEmployee.cshtml
@model Employee

<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">FirstName</th>
            <th scope="col">LastName</th>
            <th scope="col">Address</th>
            <th scope="col">PhoneNo</th>
            <th scope="col">DOB</th>
            <th scope="col">Age</th>
            <th scope="col">Designation</th>
            <th scope="col">Basic Salary</th>
            <th scope="col">Fuel Allowance</th>
            <th scope="col">Housing</th>
            <th scope="col">Overtime Rate</th>
            <th scope="col">Joining Date</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">@Model.ID</th>
            <td>@Model.FirstName</td>
            <td>@Model.LastName</td>
            <td>@Model.Address</td>
            <td>@Model.PhoneNo</td>
            <td>@Model.DateOfBirth</td>
            <td>@Model.Age</td>
            <td>@Model.Designation</td>
            <td>@Model.BasicSalary</td>
            <td>@Model.FuelAllowence</td>
            <td>@Model.Housing</td>
            <td>@Model.OverTimeHourlyRate</td>
            <td>@Model.JoiningDate</td>
        </tr>
    </tbody>
</table>

<div class="text-center w-100 mt-5"> <a type="submit" class="btn btn-primary w-75" asp-controller="EmployeeDashBoard" asp-action="Index">Go back to Home</a></div>

decoderslash_erp/Views/EmployeeDashBoard/delete_by_id_form.cshtml
<span>@ViewData["response"]</span>

<h1>Delete Employee</h1>

<form method="post" asp-controller="EmployeeDashBoard" asp-action="DeleteEmployee">
    <div class="row g-3 align-items-center mb-3 ml-5 mt-5">
      <div class="col-auto">
            <label for="delete_id" class="col-form-label">ID</label>
      </div>
      <div class="col-auto">
            <input type="number" id="delete_id" class="form-control" name="id" aria-describedby="delete_id">
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<div class="text-center w-100 mt-5"> <a type="submit" class="btn btn-primary w-75" asp-controller="EmployeeDashBoard" asp-action="Index">Go back to Home</a></div>

decoderslash_erp/Views/EmployeeDashBoard/search_by_id_form.cshtml
<span>@ViewData["response"]</span>

<h1>Search Employee</h1>

<form method="post" asp-controller="EmployeeDashBoard" asp-action="SearchEmployee">
    <div class="row g-3 align-items-center mb-3 ml-5 mt-5">
      <div class="col-auto">
            <label for="search_id" class="col-form-label">ID</label>
      </div>
      <div class="col-auto">
            <input type="number" id="search_id" class="form-control" name="id" aria-describedby="search_id">
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<div class="text-center w-100 mt-5"> <a type="submit" class="btn btn-primary w-75" asp-controller="EmployeeDashBoard" asp-action="Index">Go back to Home</a></div>