decoderslash_erp/Models/AccquireEmp.cs
using System.ComponentModel.DataAnnotations;

namespace decoderslash_erp.Models
{
    public class AccquireEmp
    {
        public List<Employee> emp { get; set; }
        [Required]
        public int TeamId { get; set; }
        [Required]
        public int empid { get; set; }
    }

}

decoderslash_erp/Controllers/ProjectManagerController.cs
using decoderslash_erp.Data;
using decoderslash_erp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Text.Json;
using decoderslash_erp.Interfaces;

namespace decoderslash_erp.Controllers
{
    public class ProjectManagerController : Controller
    {
        private readonly decoderslash_erpContext _context;
        private readonly IProjectManagerRepo _repo;
        public ProjectManagerController(decoderslash_erpContext context, IProjectManagerRepo repo)
        {
            _context = context;
            _repo = repo;
        }

        public IActionResult GetProject()
        {
            if (!CheckSession())
                return RedirectToAction("Login", "Login");
            if (!CheckAccess())
                return RedirectToAction("Error", "Home");
            Employee emp = JsonSerializer.Deserialize<Employee>(HttpContext.Session.GetString("Data")!)!;
            return View(_repo.GetProjects(emp));
        }

        public IActionResult AccquireEmp()
        {
            if (!CheckSession())
                return RedirectToAction("Login", "Login");
            if (!CheckAccess())
                return RedirectToAction("Error", "Home");
            return View(new AccquireEmp {emp =  _repo.FetchAllEmp() });
        }

        public bool CheckAccess()
        {
            String emp = HttpContext.Session.GetString("Designation")!;
            if (!emp!.Equals("Project_Manager"))
            {
                HttpContext.Session.SetString("ErrorHead", "Access Denied");
                HttpContext.Session.SetString("ErrorPara", "Looks you are trying to Access something which you should not be Accessing Be Carefull");
                return false;
            }
            return true;
        }

        public IActionResult GetProjDetails(int id)
        {
            if (!CheckSession())
                return RedirectToAction("Login", "Login");
            if (!CheckAccess())
                return RedirectToAction("Error", "Home");
            Project? proj = _repo.GetProject(id);
            if (proj == null)
            {

                HttpContext.Session.SetString("ErrorHead", "We love you tried");
                HttpContext.Session.SetString("ErrorPara", "We admire your hacking skills but we got ourseleves covered");
                return RedirectToAction("Error", "Home");

            }
            return View(new ProjectDetcs { proj = proj!});
        }
        [HttpPost]
        public IActionResult AddTask(ProjectDetcs det)
        {
            if (!CheckSession())
                return RedirectToAction("Login", "Login");
            if (!CheckAccess())
                return RedirectToAction("Error", "Home");
            Employee emp = JsonSerializer.Deserialize<Employee>(HttpContext.Session.GetString("Data")!)!;
            _repo.FillData(_context, emp.ID);
            det.task.ProjectID = det.Kc;
            _repo.AddTask(det.task);

            return RedirectToAction("GetProjDetails", new { id = det.Kc });
        }


        public bool CheckSession()
        {
			if (HttpContext.Session.GetString("Cred") == null)
			{
				return false;
			}
            return true;
		}

        public IActionResult GetTeam()
        {
            if (!CheckSession())
                return RedirectToAction("Login", "Login");
            if (!CheckAccess())
                return RedirectToAction("Error", "Home");
            Employee emp = JsonSerializer.Deserialize<Employee>(HttpContext.Session.GetString("Data")!)!;
            return View(_repo.GetTeams(emp.ID));
        }

        [HttpPost]
        public IActionResult AccquireEmp(AccquireEmp emp)
        {
            if (!CheckSession())
                return RedirectToAction("Login", "Login");
            if (!CheckAccess())
                return RedirectToAction("Error", "Home");
            Employee emps = JsonSerializer.Deserialize<Employee>(HttpContext.Session.GetString("Data")!)!;
            _repo.FillData(_context, emps.ID);
            _repo.acqemp(emp.empid, emp.TeamId);
            return View(new AccquireEmp { emp = _repo.FetchAllEmp()});
        }
    }
}

decoderslash_erp/Views/ProjectManager/AccquireEmp.cshtml
@{
    ViewData["Title"] = "Acquire Employee";
}

@model AccquireEmp
<div class="container-fluid">
    <h3 class="text-center m-5">Employees</h3>

    @{
        foreach (Employee emp in Model.emp)
        {
            <partial name="_ShowEmployee" model="@emp" />
        }

    }

    <div class="container-fluid w-50 flex-grow-1">
        <h1 class="text-center text-info m-2">Acquire Emp</h1>
        @{
            if (ViewData["Done"] != null)
            {
                <h3 class="text-center text-capitalize text-info">Task Added Successfully</h3>
            }
        }

        <form method="post" asp-controller="ProjectManager" asp-action="AccquireEmp">
            <div asp-validation-summary="All">
            </div>
            <div class="mb-3">
                <label asp-for="TeamId" class="form-label">TeamId</label>
                <input asp-for="TeamId" class="form-control" required>
            </div>
            <div class="mb-3">
                <label asp-for="empid" class="form-label">Employee ID</label>
                <input asp-for="empid" class="form-control" required>
            </div>
            <div class=" = text-center w-100 mt-2">
                <button type="submit" class="btn btn-primary w-75">Add</button>
            </div>
        </form>
    </div>
</div>

decoderslash_erp/Views/ProjectManager/GetProjDetails.cshtml
@{
    ViewData["Title"] = "Details";
}

@model ProjectDetcs
<div class="container-fluid">
    <h3 class="text-center m-5">Project @Model.proj.Name</h3>

    <h3 class="text-center">Teams</h3>
    @{
        foreach (Team team in Model.proj.teams)
        {
            <partial name="_TeamDetails" model="@team" />
        }
        
    }
    <h3 class="m-5">Project Details</h3>
    <ul class="list-group">
        <li class="list-group-item">Project Name : @Model.proj.Name</li>
        <li class="list-group-item">Start Date : @Model.proj.StartDate</li>
        <li class="list-group-item">End Date : @Model.proj.EndDate</li>
    </ul>
    <a class="btn btn-info m-5" target="_blank" asp-controller="#" asp-action="#">Download Proposal</a>

    <h3 class="text-center">Tasks</h3>

    <div class="list-group">
        @{

            foreach (Tasks task in @Model.proj.task)
            {
                @if (task.isCompleted) continue;
                <div  class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">@task.TaskName</h5>
                        <small>Click on it to Complete The Task</small>
                    </div>
                    <p class="mb-1">@task.details</p>
                    <small>Issue : @task.isIssue</small>
                </div>
            }
        }
    </div>

    <div class="container-fluid w-50 flex-grow-1">
    <h1 class="text-center text-info">Add Task</h1>
    @{
        if (ViewData["Done"] != null)
        {
            <h3 class="text-center text-capitalize text-info">Task Added Successfully</h3>
        }
    }

    <form method="post" asp-controller="ProjectManager" asp-action="AddTask">
        <div asp-validation-summary="All">
        </div>
        <div class="mb-3">
            <label asp-for="task.TaskName" class="form-label">TaskName</label>
            <input asp-for="task.TaskName" class="form-control" required>
            <input asp-for="Kc" class="form-control" required hidden value="@Model.proj.ID">
        </div>
        <div class="mb-3">
            <label asp-for="task.details" class="form-label">Details</label>
            <textarea asp-for="task.details" class="form-control" required rows="10" cols="80"></textarea>
        </div>
        <div class=" = text-center w-100 mt-2">
            <button type="submit" class="btn btn-primary w-75">Add</button>
        </div>
    </form>
</div>
</div>

decoderslash_erp/Views/ProjectManager/GetProject.cshtml
@{
    ViewData["Title"] = "Project Details";
}
@model List<Project>
<div class="list-group">
        @{
            <h2 class="text-center text-danger">Project List</h2>

            @if(Model.Count == 0)
            {
                <h1 class="text-center text-info">Woah Empty List</h1>
                <p>
                Good work champ you have done it all.
                </P>    
            }
            foreach(Project task in @Model)
            {
                <a asp-action="GetProjDetails" asp-controller="ProjectManager" asp-route-id="@task.ID" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">@task.Name</h5>
                        <small>Click on it to See Details</small>
                    </div>
                </a>
            }
        }
 </div>

decoderslash_erp/Views/ProjectManager/GetTeam.cshtml
@{
    ViewData["Title"] = "Team Details";
}
@model List<Team>
<div class="list-group">
        @{
            <h2 class="text-center text-danger">Team List</h2>

            @if(Model.Count == 0)
            {
                <h1 class="text-center text-info">Woah Empty List</h1>
                <p>
                You need to be good Project Manager
                </P>    
            }
            foreach(Team task in @Model)
            {
                <div asp-action="GetTeamDetails" asp-controller="ProjectManager" asp-route-id="@task.ID" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">ID: @task.ID  Name : @task.TeamName</h5>
                    </div>
                </div>
            }
        }
 </div>